# Generated by Django 4.1.7 on 2024-06-26 07:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="data_joined",
            new_name="date_joined",
        ),
    ]
